version: '3.8'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=advisor
      - MYSQL_ROOT_DATABASE=advisor
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local
