version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/data
    environment:
      - QDRANT__STORAGE__PERSISTENT_STORAGE_PATH=/qdrant/data

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  qdrant_data:
  redis_data: