import type { Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"

import "@ui/styles/globals.css"

import { TooltipProvider } from "@ui/components/ui/tooltip"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <TooltipProvider>
        <html lang="en">
          <body className="">{children}</body>
        </html>
      </TooltipProvider>
    </ClerkProvider>
  )
}
