import type { Metadata } from "next"

import "@repo/ui/styles.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className="overflow-y-scroll">{children}</body>
		</html>
	)
}
