name: Test
on:
  push:
    branches: 
      - main
  pull_request_target:
    branches:
      - main
jobs:

  test:
    name: run-tests
    runs-on: ubuntu-latest
    environment: GH_ACTION
    env:
      TURBO_REMOTE_ONLY: true
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: bun i
        
        
      - run: bun run db:generate
        
      - name: Run Type Check
        run: bun run type-check
      
      - name: Run Linting
        run: bun run lint

      - name: Run Tests
        run: bun run test
